plugins {
    id 'java'
    id 'maven-publish'
    id 'com.gtnewhorizons.retrofuturagradle' version '1.4.1'
}

version = "1.0-1.8.9"
group = "net.johnseagull.pickup"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(8)
}

minecraft {
    version = "1.8.9"
    mappings = "stable_22"
    
    mixin {
        add sourceSets.main, "pickup.mixins.refmap.json"
    }
}

repositories {
    mavenCentral()
    maven {
        name = "CleanroomMC"
        url = "https://maven.cleanroommc.com"
    }
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
    inputs.property "version", project.version

    filesMatching('mcmod.info') {
        expand 'version': project.version
    }
}
